config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  get 'orders/show'
  get 'carts/create'
  devise_for :users
  root "packs#index"
  resources :packs, only: [:index, :show]
  resources :carts, only: [:create, :index, :destroy]
  resources :orders, only: [:create, :show, :index]
  get 'home/index'
  get "/mypage" => "home#mypage"


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :pack

  def verified_save
    sample_carts = self.user.carts
    remain_cart = sample_carts.find_by(pack_id: self.pack_id)

    if remain_cart.present?
      sum_quantity = remain_cart.quantity + self.quantity.to_i

      remain_cart.update(quantity: sum_quantity)
    else

      self.save
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  has_many :order_items, dependent: :destroy
  has_many :packs, through: :order_items
  
  enum status: [:before_payment, :processed, :completed, :failed]


  def product_price
    result = 0
    self.order_items.each do |order_item|
    result+=order_item.quantity*order_item.pack.price
    end
    return result
  end

  def shipping_fee
    if self.product_price > 500
      result = 0
  else
      result = 80
  end
    return result
  end

  def total_price
    result = self.shipping_fee + self.product_price
    return result
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :pack
end

app/models/pack.rb
class Pack < ApplicationRecord
    has_one_attached :image

    validates :product_name, :company_name, :price, presence: true
    validates :is_publish, exclusion: {in:[nil]}

    scope :published, -> {Pack.where(is_publish: true)}
    scope :unpublished, -> {Pack.where(is_publish: false)}

    has_many :carts, dependent: :destroy
    has_many :users, through: :carts
    has_many :order_items, dependent: :destroy
    has_many :orders, through: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts, dependent: :destroy
  has_many :packs, through: :carts
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @carts = current_user.carts

    @product_price=0
    @carts.each do |cart|
    @product_price+=cart.pack.price*cart.quantity
    end
    if @product_price > 500
        @shipping_fee = 0
    else
        @shipping_fee = 80
    end
    @total_price=@product_price+@shipping_fee
  end

  def create
    cart = Cart.new(
      pack_id: params[:pack_id],
      user_id: current_user.id,
      quantity: params[:quantity]
    )
    
    cart.verified_save

    flash[:notice]="Successfully saved. Would you like to check it out?"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!, only: [:mypage]

  def index
  end
  def mypage
    @user=current_user
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @orders = current_user.orders  
  end

  def create
    order = Order.create(user_id: current_user.id)
    carts = Cart.where(id: params[:cart_id])

    carts.each do |cart|
      order.order_items.create(pack_id: cart.pack.id, quantity: cart.quantity)
    end
    carts.destroy_all
    redirect_to "/orders/#{order.id}"
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  def index
    @packs = Pack.all
  end

  def show
    @pack = Pack.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def item_to_currency(object)
        number_to_currency(object.quantity*object.pack.price, precision: 0)
        
    end

    def cart_to_currency (object)
        number_to_currency(object.pack.price * object.quantity, precision: 0)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/index.html.erb
<div class="container">
<div class="mt-6 mb-2 is-size-1"> 
<i class="fas fa-clipboard-check icon is-large"></i>
Shoping Cart
</div>
</div>

<hr>

  

<div class="container" style="width: 90%">
    <div class="table-container ">
<table class = "table is-striped is-hoverable is-fullwidth">
               <thead>
                  <tr>
                     <th style="width: 50%">Produnct Name</th>
                     <th >Price</th>
                     <th>Quantity</th>
                     <th>Total</th>
                     <th></th>
                  </tr>
               </thead>
               <% if @carts.present? %>
               <tbody>
               <%@carts.each do |cart|%>
                  <tr>
                     <td><%=cart.pack.product_name%></td>
                     <td><%=number_to_currency(cart.pack.price, precision: 0)%></td>
                     <td><%=cart.quantity%></td>
                     <td><%=cart_to_currency(cart)%></td>
                     <td>
                     <a href="/carts/<%=cart.id%>" data-method="delete" data-confirm="Dude, really?">
                     <i class="far fa-times-circle"></i></a>
                     </td>
                  </tr>
                  <% end %>
               </tbody>
            </table>
</div>
</div>
<hr>


<div class="container">
   <div class="columns mt-6">
      <div class="column is-6  ">
      <p class="title ml-6">Sum of price</p>
      <p class="title ml-6">Shipping Fee</p>
      <p class="title ml-6">Final price</p>
      </div>
      <div class="column has-text-right">
      <p class="title mr-6"><%=number_to_currency(@product_price, precision: 0)%></p>
      <p class="title mr-6"><%=number_to_currency(@shipping_fee, precision: 0)%></p>
      <p class="title mr-6"><%=number_to_currency(@total_price, precision: 0)%></p>
      </div>
   </div>
   <hr>
      <div class="columns mt-6">
      <div class="column is-6  ">
         <a href="/packs"class="button is-link is-outlined">Add more to the cart!</a>
      </div>
      <div class="column has-text-right">
         <form action="/orders" method="post">
            <%=hidden_field_tag :authenticity_token, form_authenticity_token%>
            <%@carts.each do |cart|%>
            <input type="hidden" name="cart_id[]" value="<%=cart.id%>">
            <% end %>
            <button type="submit" class="button is-link is-outlined">ORDER</button>
         </form>
      </div>
   </div>
</div>
<% end %>

app/views/home/index.html.erb
Let us add carousel here later
make it super cool :D

app/views/home/mypage.html.erb
<div class="container mt-6">
    <div class="columns">
        <div class="column is-2">
            <aside class="menu">
            <p class="menu-label">
                General
            </p>
            <ul class="menu-list">
                <li><a>Dashboard</a></li>
                <li><a>Customers</a></li>
            </ul>
            <p class="menu-label">
                Transactions
            </p>
            <ul class="menu-list">
                <li><a>Payments</a></li>
                <li><a>Transfers</a></li>
                <li><a>Balance</a></li>
            </ul>
            </aside>
        </div>
        <div class="column">
            <div class="columns is-mobile is-centered">
            <div class="column has-text-centered">
                <article class="tile is-child notification is-info">
                    <p class="title has-text-centered">My Profile</p>
                    <button class="button is-info is-inverted ">Check</button>
                    <div class="content">
                    <!-- Content -->
                    </div>
                </article>
            </div>
            <div class="column has-text-centered">
                <article class="tile is-child notification is-info">
                    <p class="title has-text-centered ">Order History</p>
                    <a href="/orders" class="button is-info is-inverted ">Check</a>

                </article>
      </div>
        </div>
    </div>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="notification is-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="notification is-warning">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<section class="hero is-dark is-small" style="background-image:url('back.jpg') ">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            
              <%=link_to "Equipments", packs_path, class: "navbar-item is-active"%>
            

            <%if user_signed_in?%>    
                           
            <a href="/carts" class="navbar-item"> 
            <i class="fas fa-shopping-cart"></i>
           </a>
          <div class="dropdown">
          <div class="dropdown is-hoverable mt-2">
            <div class="dropdown-trigger">
              <button class="button" aria-haspopup="true" aria-controls="dropdown-menu4">
                <span><%=current_user.email%></span>
                <span class="icon is-small">
                  <i class="fas fa-angle-down" aria-hidden="true"></i>
                </span>
              </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu4" role="menu">
              <div class="dropdown-content">
                <div class="dropdown-item">
                  <%=link_to "My page","/mypage", class:"button is-small is-fullwidth is-black is-inverted"%>
                </div>
                      <div class="dropdown-item">
                  <%=link_to "Log out",destroy_user_session_path, method: :delete, class:"button is-small is-fullwidth is-danger is-inverted"%>
                </div>
              </div>
            </div>
          </div>


                      <% else %>
                      <span class="navbar-item">
                          <%=link_to "Log in",new_user_session_path, class:"button is-link is-light"%>
                      </span>
                                  <span class="navbar-item">
                                  
                          <%=link_to "Sign up",new_user_registration_path, class:"button is-link is-light"%>
                      </span>
                      <% end %>

                    </div>
                  </div>
                </div>
              </nav>
            </div>

            <!-- Hero content: will be in the middle -->
            <div class="hero-body">
            
              <div class="container has-text-centered">
              <a href="/">
                <img src="logo.png" alt="logo" style="width:300px; height:300px;">
              </a>
              </div>
            </div>

  <!-- Hero footer: will stick at the bottom -->
  <%# <div class="hero-foot">
    <nav class="tabs">
      <div class="container">
        <ul>
          <li class="is-active"><a>Weight training</a></li>
          <li><a>Cardio</a></li>
          <li><a>Flexibility</a></li>
        </ul>
      </div>
    </nav>
  </div> %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Machine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>

  </head>

  <body>
  <%=render "layouts/header"%>
    <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.4/dist/js/bulma-carousel.min.js"></script>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <div class="columns ">
    <div class="column is-12 mt-5">
        <p class="is-size-3 has-text-centered">Order History</p>
        <div class="tile">
            <div class="tile is-parent is-vertical">
                <article class="tile is-child notification is-primary">
                <p class="is-size-4">Normal orders will be displayed here.<br>
                For special orders, please check the subscription under the menu </p>
                </article>
            </div>
        </div>    
    </div>
  </div>
</div>

<div class="container">
   <div class="columns ">
    <div class="column is-12 mt-5">
      <table class="table is-hoverable is-fullwidth">
        <tr class="th">
            <th>Order date</th>
            <th>recipient</th>
            <th>receiving location</th>
            <th>status</th>
            <th>details</th>
        </tr>
        <%@orders.each do |order|%>
        <tr>
            <td><%=order.created_at.strftime("%F")%></td>
            <td><%=order.name%></td>
            <td><%=order.email%></td>
            <td><%=order.status%></td>
            <td><a href="/orders/<%=order.id%>" class="button is-outlined is-primary">Details</a></td>
        </tr>
        <%end%>
      </table>
    </div>
   </div> 
</div>

app/views/orders/show.html.erb
<div class="container">
    <div class="columns is-centered">
        <div class="column is-8 mt-4 ">
            <p class="is-size-1 has-text-centered">Confirm your order</p>
            <%@order.order_items.each do |item|%>
            <div class="card mt-3">
            <header class="card-header">
                <p class="card-header-title">
                <%=item.pack.product_name%>
                </p>
            </header>
            <div class="card-content ">
                <div class="card-title ">
                    <%=item.pack.company_name%>
                </div>
                <div class="content">
                Quantity: <%=item.quantity%>
                <br>
                </div>
            </div>
                <a href="#" class="button is-link is-rounded is-outlined ml-3 is-small">Edit</a>
                <a href="#" class="button is-danger is-rounded is-outlined ml-3 is-small">Delete</a>
                <hr>
                <p class="is-size-4 ml-3">Price: <%=item_to_currency(item)%></p>
                <br>
            </div>
            <% end %>
        </div>
    </div>

    <div class="columns is-centered">
        <div class="column is-8 ">
            <p class="has-text-3">Shipping info confirmation</p>
            <form>
                <div class="field">
                    <label class="label">Name</label>
                <div class="control">
                    <input class="input" type="text" id="name" name="name">
                </div>
                </div>

                <div class="field">
                    <label class="label">Contact</label>
                <div class="control">
                    <input class="input" type="number" id="phone" name="phone">
                </div>
                </div>

                <div class="field">
                    <label class="label">Email</label>
                <div class="control">
                    <input class="input" type="email" id="email" name="email">
                </div>
                </div>
                <div class="field">
                    <label class="label">Address</label>
                    <a href="#" class="button is-dark is-outlined" id="search_address_btn">Search Address</a>
                <div class="control mt-3">
                    <input class="input mt-1" type="text" id="post_code" name="post_code" placeholder="post code">
                    <input class="input mt-2" type="text" id="address_1" name="address_1" placeholder="address 1">
                    <input class="input mt-2" type="text" id="address_2" name="address_2" placeholder="address 2">
                </div>
                </div>
            </form>
        </div>

    </div>
    <hr>
    <p class="is-size-3">Checkout price</p><br>
    <div class="columns is-centered">
      <div class="column is-4  ">
      <p class="subtitle">Total Product Price</p>
      <p class="subtitle">Shipping Fee</p>
      <p class="subtitle">Final Price</p>
      </div>
      <div class="column is-4 has-text-right">
      <p class="subtitle mr-4"><%=number_to_currency(@order.product_price, precision: 0)%></p>
      <p class="subtitle mr-4"><%=number_to_currency(@order.shipping_fee, precision: 0)%></p>
      <p class="subtitle mr-4"><%=number_to_currency(@order.total_price, precision: 0)%></p>
      </div>
   </div>
      </div>
    </div>
    <div class="columns is-centered">
        <div class="column is-6">
            <a href="#" class="button my-4 is-fullwidth is-warning is-large ">Pay</a>
        </div>
    </div>
</div>






<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    $("#search_address_btn").on("click", function(e){
        e.preventDefault();
        postCodePopup()
    }
    )

    function postCodePopup() {
            new daum.Postcode({
        oncomplete: function(data) {
        }
    }).open();
    }

</script>

app/views/packs/index.html.erb
<section class="section">
<div class="container">
 
 <div class="columns is-multiline mt-4">
 <%@packs.each do |pack|%>
   <div class="column is-3">
   <div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <%if pack.image.attached?%>
      
      <%=link_to (image_tag(pack.image)),pack_path(pack) %>
      <% else %>
      <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
      <% end %>
      
    </figure>
  </div>
  <div class="card-content">
    <div class="content has-text-centered">
      <%=pack.product_name%>
      <hr>
      <%=truncate(pack.desc, length: 60, separator: " ")%>
    </div>
  </div>
</div>
    
   </div>

   <% end %>
 </div>
 
</div>
</section>

app/views/packs/show.html.erb
<div class= "container">
<div class="columns mt-4">
  <div class= "column is-6">
  <%if @pack.image.attached?%>
    <%=image_tag @pack.image %>
    </div>
    <% else %>
    <%=image_tag ("https://via.placeholder.com/649x360?text=No+image") %>
    <% end %>
  <div class= "column is-6">
    <div class="card">
        <header class="card-header">
            <p class="card-header-title has-background-link-light is-size-3 ">
            <%=@pack.product_name%>
            </p>
        </header>
                <header class="card-header">
                <p class= "card-header-title is-size-4">
            Price: <%=number_to_currency(@pack.price, precision: 0)%>
                </p>
        </header>
  <div class="card-content">
    <h5>Description</h5>
    <p class="subtitle">
      <%=@pack.desc%><br>
      <%=@pack.company_name%>
      <hr>
      <h3>Choose the quantity</h3>
      <form action="/carts" method="post">
      <%=hidden_field_tag :authenticity_token, form_authenticity_token%>
      <input type="hidden" name="pack_id" value="<%=@pack.id%>">

      <div class="form-group">
        <label for="quantity">Quantity</label>
        <select name="quantity" id="quantity" class="form-control">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        </select>
      </div>

      <button type="submit" class="is-outlined">Put it in the shopping cart</button>
      </form>

    </p>
  </div>
  <footer class="card-footer">
    <p class="card-footer-item ">
        Number of order
    </p>
  </footer>
</div>
    </div>
</div>
</div>

<script>
  <%if flash[:notice].present?%>
    result = confirm("<%=flash[:notice]%>")

    if(result){
      location.href = "/carts"
    }
  <%end%>
</script>